# Generated by Django 3.0.3 on 2020-02-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number',
            new_name='Video',
        ),
    ]
