# Generated by Django 3.0.3 on 2020-03-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200221_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Measurement',
        ),
    ]
